"""
=== PIPELINE PROVENANCE — v29 (v28b + LLM-extracted conditions) ===
v29 = submission_v28b.csv with ONLY the `conditions` column regenerated by an
LLM-RAG extractor (Mistral-7B-Instruct-v0.3 Q4, the same model as v28). All other
columns (study_type, sex, minimum_age='18 Years', maximum_age='Not Specified',
eligibility_criteria) are copied unchanged from v28b.

WHY: conditions was the weakest field by far. The submitted vocab-substring
approach scored 0.31905 on the public LB (conditions-only probe). The metric is
BioBERT cosine similarity to the GT condition list (evaluate.biobert_similarity),
which rewards clean, semantically-correct disease names. The old vocab approach:
  (a) only matched condition names seen in TRAIN GT (recall ceiling), and
  (b) grabbed non-disease noise (imaging modalities, measurements, anatomy),
dragging the embedding away from GT's clean disease names.

The LLM extractor prompts Mistral-7B with PubMedBERT-retrieved few-shot examples
from train (title+abstract -> JSON disease list), instructed to output ONLY
diseases/conditions, no imaging/devices/measurements.

EVIDENCE (leakage-free train eval, self excluded from retrieval; see cond_llm_train.py):
  vocab baseline : 0.544 train (LEAKY; vocab built from train) -> 0.319 real test
  LLM-RAG        : 0.648 train (leakage-free) -> expected ~0.6 on test
Estimated overall: ~0.707 -> ~0.75 (+0.04..0.05).

CPU NOTE: pure CPU by default (~1-2 min/article for the 7B). Set N_GPU_LAYERS=33
for GPU dev speed; output is identical.

REPRODUCE:
  python build_v29.py                 # pure CPU (competition mode)
  N_GPU_LAYERS=33 python build_v29.py  # GPU dev speed
INPUT : submission_v28b.csv
OUTPUT: submission_v29.csv
"""
import os, sys, csv, time
sys.path.insert(0, '.')
from nxml_parser import parse_nxml
from cond_llm_train import extract_conditions_llm

SRC = '/home/kkolpetinou/cohort-x-task-1/submission_v28b.csv'
OUT = '/home/kkolpetinou/cohort-x-task-1/submission_v29.csv'
FIELDNAMES = ['pmcids', 'conditions', 'study_type', 'sex',
              'minimum_age', 'maximum_age', 'eligibility_criteria']


def main():
    with open(SRC) as f:
        rows = list(csv.DictReader(f))
    print(f'Loaded {len(rows)} rows from {SRC}', flush=True)

    t0 = time.time(); changed = 0; nf = 0
    for i, r in enumerate(rows, 1):
        parsed = parse_nxml(r['pmcids'])
        if parsed is None:
            nf += 1
            continue
        # test pmcids are not in the train index, so no self-exclusion needed
        new_cond = extract_conditions_llm(parsed, exclude_pmcid=r['pmcids'])
        if new_cond != r['conditions']:
            changed += 1
        r['conditions'] = new_cond
        if i % 25 == 0:
            el = time.time() - t0; rate = i / max(el, 1)
            print(f'  [{i}/{len(rows)}] {el:.0f}s, ETA {(len(rows)-i)/max(rate,0.001):.0f}s, changed={changed}', flush=True)

    with open(OUT, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=FIELDNAMES)
        w.writeheader()
        w.writerows([{k: r.get(k, '') for k in FIELDNAMES} for r in rows])
    print(f'\nWrote -> {OUT} (conditions changed on {changed}/{len(rows)}, {nf} parse-fail kept)')


if __name__ == '__main__':
    main()
